function integradaplot(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 22-Nov-2016 12:05:43

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on',...
    'XTickLabel',{'0','1ms','2ms','3ms','4ms','5ms','6ms','7ms','8ms','9ms','10ms'},...
    'XGrid','on');
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-0.0001 0.0008]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',2,'Color',[1 0 0]);

% Create xlabel
xlabel('Tiempo [s]');

% Create ylabel
ylabel('Amplitud [V]');

% Create title
title('Señal Moduladora Integrada');

