function modulaciont(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 24-Nov-2016 12:51:23

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.12895178197065 0.582118996243906 0.775 0.341162790697674]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',1);

% Create xlabel
xlabel('Tiempo [s]');

% Create ylabel
ylabel('Amplitud [V]');

% Create title
title('Modulación con desviación en frecuencia de 75 y 100 Hz respectivamente');

% Create subplot
subplot1 = subplot(2,1,2,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(X1,Y2,'Parent',subplot1,'LineWidth',1);

% Create xlabel
xlabel('Tiempo [s]');

% Create ylabel
ylabel('Amplitud [V]');

