function modulacionfplot(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 24-Nov-2016 12:44:33

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1,'YGrid','on','XScale','log',...
    'XMinorTick','on',...
    'XMinorGrid','on',...
    'XGrid','on');
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot1,[100 50000]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot1,[0 1.5]);
box(subplot1,'on');
hold(subplot1,'all');

% Create semilogx
semilogx(X1,Y1,'Parent',subplot1,'LineWidth',2);

% Create xlabel
xlabel('Frecuencia [Hz]');

% Create ylabel
ylabel('Amplitud');

% Create title
title('Espectro Modulación con 75Hz de desviación');

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1,'YGrid','on',...
    'XTickLabel',{'100Hz','1KHz','10KHz','100KHz'},...
    'XScale','log',...
    'XMinorTick','on',...
    'XMinorGrid','on',...
    'XGrid','on');
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot2,[100 50000]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot2,[0 1.5]);
box(subplot2,'on');
hold(subplot2,'all');

% Create semilogx
semilogx(X1,Y2,'Parent',subplot2,'LineWidth',2);

% Create xlabel
xlabel('Frecuencia [Hz]');

% Create ylabel
ylabel('Amplitud');

% Create title
title('Espectro Modulación con 100Hz de desviación');

