function moduladoraplot(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 22-Nov-2016 11:55:31

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1,'YGrid','on',...
    'XTickLabel',{'0','1ms','2ms','3ms','4ms','5ms','6ms','7ms','8ms','9ms','10ms'},...
    'XGrid','on');
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot1,[0 0.01]);
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',2);

% Create xlabel
xlabel('Tiempo [s]');

% Create ylabel
ylabel('Amplitud [V]');

% Create title
title('Señal Moduladora');

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1,'YGrid','on',...
    'XTickLabel',{'0','5Khz','10Khz','15Khz','20Khz','25Khz','30Khz','35Khz','40Khz','45Khz','50Khz'},...
    'XGrid','on');
ylim(subplot2,[0 1]);
box(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(X2,Y2,'Parent',subplot2,'LineWidth',2);

% Create xlabel
xlabel('Frecuencia[Hz]');

% Create ylabel
ylabel('Amplitud');

% Create title
title('Frecuencia Señal Moduladora');

