function modulacionruido(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 24-Nov-2016 13:03:55

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
box(subplot1,'on');
hold(subplot1,'all');

% Create plot
plot(X1,Y1,'Parent',subplot1,'LineWidth',1);

% Create xlabel
xlabel('Tiempo [s]');

% Create ylabel
ylabel('Amplitud [V]');

% Create title
title('Señal modulada con ruido AWGN 15dB y 30dB SNR respectivamente');

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
box(subplot2,'on');
hold(subplot2,'all');

% Create plot
plot(X1,Y2,'Parent',subplot2,'LineWidth',1);

% Create xlabel
xlabel('Tiempo [s]');

% Create ylabel
ylabel('Amplitud [V]');

