function portadoraplot(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 22-Nov-2016 12:02:18

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on');
%% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 0.005]);
%% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[-2 2]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',2);

% Create xlabel
xlabel('Tiempo [s]');

% Create ylabel
ylabel('Amplitud [V]');

% Create title
title('Señal Portadora');

